services:
  blog:
    depends_on:
      - blog_db
    container_name: blog
    restart: unless-stopped
    image: mute/blog:latest
    expose:
      - 80
    environment:
      - WORDPRESS_DB_HOST=blog_db
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - VIRTUAL_HOST=${BLOG_DOMAIN},www.${BLOG_DOMAIN}
      - LETSENCRYPT_HOST=${BLOG_DOMAIN},www.${BLOG_DOMAIN}
      # - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true uncomment to create separate certificate for each domain
    volumes:
      - blog_website:/var/www/html
  blog_db:
    container_name: blog_db
    restart: unless-stopped
    image: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - blog_db:/var/lib/mysql
  db_backup:
    container_name: blog_db_backup
    image: tiredofit/db-backup:latest
    volumes:
      - ./backups:/backup
    environment:
      - DB_TYPE=mysql
      - DB_HOST=blog_db
      - DB_NAME=${WORDPRESS_DB_NAME}
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_PORT=3306
      - DB_CLEANUP_TIME=8640
      - DB_DUMP_BEGIN=+1
      - SIZE_VALUE=megabytes
    restart: always
volumes:
 blog_db: null
 blog_website: null
networks:
  default:
    external:
      name: ${DOCKER_NETWORK}
